game_config:
  agents: 1
  render_mode: human
  batch_mode: false
  level: default
  host: 127.0.0.1
  port: 31000

agents_config:
  agents: DQN
  mode: train
  episodes: 50
  epochs: 5
  save_every: 10
