game_config:
  agents: 1
  render_mode: human
  batch_mode: true
  level: default
  host: 127.0.0.1
  port: 31000

agents_config:
  agents: DQN
  mode: train
  model_path: ep_420.model
  start_episode: 420
  episodes: 1000
  epochs: 1
  update_every: 1000
  epsilon: 0.25
  epsilon_decay: 0.00001
  save_every: 20
