version: "3.0"

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  update1000:
    build: .
    entrypoint: python3 main.py --expname=update1000 --train
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./exps/:/root/.MARLIO-runner/
      - ./configs/set3/update1000/config.yml:/MARLIO-runner/config.yml
      - ./configs/set3/update1000/config.json:/MARLIO-runner/config.json

  update5000:
    build: .
    entrypoint: python3 main.py --expname=update5000 --train
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./exps/:/root/.MARLIO-runner/
      - ./configs/set3/update5000/config.yml:/MARLIO-runner/config.yml
      - ./configs/set3/update5000/config.json:/MARLIO-runner/config.json

  update5000_decay:
    build: .
    entrypoint: python3 main.py --expname=update5000_decay --train
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./exps/:/root/.MARLIO-runner/
      - ./configs/set3/update5000_decay/config.yml:/MARLIO-runner/config.yml
      - ./configs/set3/update5000_decay/config.json:/MARLIO-runner/config.json

  update5000_withexplosion:
    build: .
    entrypoint: python3 main.py --expname=update5000_withexplosion --train
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./exps/:/root/.MARLIO-runner/
      - ./configs/set3/update5000_withexplosion/config.yml:/MARLIO-runner/config.yml
      - ./configs/set3/update5000_withexplosion/config.json:/MARLIO-runner/config.json
