game_config:
  agents: 1
  render_mode: human
  batch_mode: true
  level: default
  host: 127.0.0.1
  port: 31000

agents_config:
  agents: DQN
  mode: train
  episodes: 1000
  epochs: 1
  update_every: 5000
  epsilon_decay: 0.000005
  save_every: 20
